---
- name: Set up MySQL nodes for group replication
  hosts: mysql_nodes

  tags:
    - mysql

  roles:
    - role: mysql

- name: Set up ProxySQL to balance group
  hosts: mysql_proxy

  tags:
    - proxysql

  roles:
    - role: proxysql
